{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-hub-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore.name }}
  target:
    name: jupyterhub-hub-secret
  data:
    - secretKey: hub.config.JupyterHub.cookie_secret
      remoteRef:
        key: jupyterhub-secrets
        property: cookie-secret
    - secretKey: hub.config.CryptKeeper.keys
      remoteRef:
        key: jupyterhub-secrets
        property: crypto-key
    - secretKey: proxy.secretToken
      remoteRef:
        key: jupyterhub-secrets
        property: proxy-secret-token
{{- end }}